version: '3'

services:
  db:
    image: kartoza/postgis:11.0-2.5

    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - sciadro_bridge

  rabbit-mq:
    image: rabbitmq:3.7
    networks:
      - sciadro_bridge

  api:
    build: ./api
    entrypoint: /code/entrypoint-staging.sh
    volumes:
      - ./api:/code
      - static_volume:/code/static
      - media_volume:/code/data
    depends_on:
      - db
      - rabbit-mq
    environment:
      DEBUG: 0
      WAIT_HOSTS: db:5432, rabbit-mq:5672
    networks:
      - sciadro_bridge

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - static_volume:/code/static
      - media_volume:/code/data
    networks:
       - sciadro_bridge

  frontend:
    image: geosolutionsit/mapstore2:SCIADRO-2019.01.01
    networks:
      - sciadro_bridge

volumes:
  static_volume:
  media_volume:


networks:
    sciadro_bridge:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: sciadro-bridge